"""A module containing generally useful chemical data"""

atoms = {
    "Ru": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":8,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":2.2,
        "nobleGas?":False,
        "abbreviation":"Ru",
        "ionization_energy":710.2,
        " atomic_radius":178.,
        "metalloid?":False,
        "electron_affinity":101.3,
        "pearson_electronegativity":405.7,
        "Z":44,
        "hardness":304.5,
}
    "Re": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":7,
        "group":7,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.9,
        "nobleGas?":False,
        "abbreviation":"Re",
        "ionization_energy":760.,
        " atomic_radius":188.,
        "metalloid?":False,
        "electron_affinity":14.5,
        "pearson_electronegativity":387.,
        "Z":75,
        "hardness":373.,
}
    "Ra": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":2,
        "actinide?":False,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":0.9,
        "nobleGas?":False,
        "abbreviation":"Ra",
        "ionization_energy":509.3,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":88,
        "hardness":None,
}
    "Rb": {
        "lanthanide?":False,
        "alkali_metal?":True,
        "valence":1,
        "group":1,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":0.82,
        "nobleGas?":False,
        "abbreviation":"Rb",
        "ionization_energy":403.,
        " atomic_radius":265.,
        "metalloid?":False,
        "electron_affinity":46.9,
        "pearson_electronegativity":224.9,
        "Z":37,
        "hardness":178.1,
}
    "Rn": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":18,
        "actinide?":False,
        "nonmetal?":True,
        "period":6,
        "pauling_electronegativity":None,
        "nobleGas?":True,
        "abbreviation":"Rn",
        "ionization_energy":1037.,
        " atomic_radius":120.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":518.5,
        "Z":86,
        "hardness":518.5,
}
    "Rh": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":9,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":2.28,
        "nobleGas?":False,
        "abbreviation":"Rh",
        "ionization_energy":719.7,
        " atomic_radius":173.,
        "metalloid?":False,
        "electron_affinity":109.7,
        "pearson_electronegativity":414.7,
        "Z":45,
        "hardness":305.,
}
    "Be": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":2,
        "actinide?":False,
        "nonmetal?":False,
        "period":2,
        "pauling_electronegativity":1.57,
        "nobleGas?":False,
        "abbreviation":"Be",
        "ionization_energy":899.5,
        " atomic_radius":112.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":449.75,
        "Z":4,
        "hardness":449.75,
}
    "Ba": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":2,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":0.89,
        "nobleGas?":False,
        "abbreviation":"Ba",
        "ionization_energy":502.9,
        " atomic_radius":253.,
        "metalloid?":False,
        "electron_affinity":13.95,
        "pearson_electronegativity":258.4,
        "Z":56,
        "hardness":244.5,
}
    "Bi": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":15,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.02,
        "nobleGas?":False,
        "abbreviation":"Bi",
        "ionization_energy":703.,
        " atomic_radius":143.,
        "metalloid?":False,
        "electron_affinity":91.2,
        "pearson_electronegativity":397.,
        "Z":83,
        "hardness":306.,
}
    "Br": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":17,
        "actinide?":False,
        "nonmetal?":True,
        "period":4,
        "pauling_electronegativity":2.96,
        "nobleGas?":False,
        "abbreviation":"Br",
        "ionization_energy":1139.9,
        " atomic_radius":94.,
        "metalloid?":False,
        "electron_affinity":324.6,
        "pearson_electronegativity":732.3,
        "Z":35,
        "hardness":407.6,
}
    "H": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":1,
        "group":1,
        "actinide?":False,
        "nonmetal?":True,
        "period":1,
        "pauling_electronegativity":2.2,
        "nobleGas?":False,
        "abbreviation":"H",
        "ionization_energy":1312.,
        " atomic_radius":53.,
        "metalloid?":False,
        "electron_affinity":72.8,
        "pearson_electronegativity":692.4,
        "Z":1,
        "hardness":619.6,
}
    "P": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":15,
        "actinide?":False,
        "nonmetal?":True,
        "period":3,
        "pauling_electronegativity":2.19,
        "nobleGas?":False,
        "abbreviation":"P",
        "ionization_energy":1011.8,
        " atomic_radius":98.,
        "metalloid?":False,
        "electron_affinity":72.,
        "pearson_electronegativity":542.,
        "Z":15,
        "hardness":470.,
}
    "Os": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":8,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.2,
        "nobleGas?":False,
        "abbreviation":"Os",
        "ionization_energy":840.,
        " atomic_radius":185.,
        "metalloid?":False,
        "electron_affinity":106.1,
        "pearson_electronegativity":473.,
        "Z":76,
        "hardness":367.,
}
    "Hg": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":12,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.,
        "nobleGas?":False,
        "abbreviation":"Hg",
        "ionization_energy":1007.1,
        " atomic_radius":171.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":503.55,
        "Z":80,
        "hardness":503.55,
}
    "Ge": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":14,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":2.01,
        "nobleGas?":False,
        "abbreviation":"Ge",
        "ionization_energy":762.,
        " atomic_radius":125.,
        "metalloid?":True,
        "electron_affinity":119.,
        "pearson_electronegativity":440.,
        "Z":32,
        "hardness":321.,
}
    "Gd": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.2,
        "nobleGas?":False,
        "abbreviation":"Gd",
        "ionization_energy":593.4,
        " atomic_radius":233.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":322.,
        "Z":64,
        "hardness":272.,
}
    "Ga": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":13,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.81,
        "nobleGas?":False,
        "abbreviation":"Ga",
        "ionization_energy":578.8,
        " atomic_radius":136.,
        "metalloid?":False,
        "electron_affinity":28.9,
        "pearson_electronegativity":303.9,
        "Z":31,
        "hardness":275.,
}
    "Pr": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":4,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.13,
        "nobleGas?":False,
        "abbreviation":"Pr",
        "ionization_energy":527.,
        " atomic_radius":247.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":288.,
        "Z":59,
        "hardness":238.,
}
    "Pt": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":10,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.28,
        "nobleGas?":False,
        "abbreviation":"Pt",
        "ionization_energy":870.,
        " atomic_radius":177.,
        "metalloid?":False,
        "electron_affinity":205.3,
        "pearson_electronegativity":538.,
        "Z":78,
        "hardness":332.,
}
    "Pu": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":None,
        "actinide?":True,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":1.28,
        "nobleGas?":False,
        "abbreviation":"Pu",
        "ionization_energy":584.7,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":94,
        "hardness":None,
}
    "C": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":14,
        "actinide?":False,
        "nonmetal?":True,
        "period":2,
        "pauling_electronegativity":2.55,
        "nobleGas?":False,
        "abbreviation":"C",
        "ionization_energy":1086.5,
        " atomic_radius":67.,
        "metalloid?":False,
        "electron_affinity":153.9,
        "pearson_electronegativity":620.2,
        "Z":6,
        "hardness":466.3,
}
    "Pb": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":14,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.33,
        "nobleGas?":False,
        "abbreviation":"Pb",
        "ionization_energy":715.6,
        " atomic_radius":154.,
        "metalloid?":False,
        "electron_affinity":35.1,
        "pearson_electronegativity":375.3,
        "Z":82,
        "hardness":340.3,
}
    "Pa": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":None,
        "actinide?":True,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":1.5,
        "nobleGas?":False,
        "abbreviation":"Pa",
        "ionization_energy":568.,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":91,
        "hardness":None,
}
    "Pd": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":10,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":2.2,
        "nobleGas?":False,
        "abbreviation":"Pd",
        "ionization_energy":804.4,
        " atomic_radius":169.,
        "metalloid?":False,
        "electron_affinity":53.7,
        "pearson_electronegativity":429.,
        "Z":46,
        "hardness":375.3,
}
    "Cd": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":12,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":1.69,
        "nobleGas?":False,
        "abbreviation":"Cd",
        "ionization_energy":867.8,
        " atomic_radius":161.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":433.9,
        "Z":48,
        "hardness":433.9,
}
    "Po": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":16,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.,
        "nobleGas?":False,
        "abbreviation":"Po",
        "ionization_energy":812.1,
        " atomic_radius":135.,
        "metalloid?":True,
        "electron_affinity":183.3,
        "pearson_electronegativity":497.7,
        "Z":84,
        "hardness":314.4,
}
    "Pm": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":None,
        "nobleGas?":False,
        "abbreviation":"Pm",
        "ionization_energy":540.,
        " atomic_radius":205.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":295.,
        "Z":61,
        "hardness":245.,
}
    "Ho": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.23,
        "nobleGas?":False,
        "abbreviation":"Ho",
        "ionization_energy":581.,
        " atomic_radius":226.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":315.,
        "Z":67,
        "hardness":266.,
}
    "Hf": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":4,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.3,
        "nobleGas?":False,
        "abbreviation":"Hf",
        "ionization_energy":658.5,
        " atomic_radius":208.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":329.25,
        "Z":72,
        "hardness":329.25,
}
    "K": {
        "lanthanide?":False,
        "alkali_metal?":True,
        "valence":1,
        "group":1,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":0.82,
        "nobleGas?":False,
        "abbreviation":"K",
        "ionization_energy":418.8,
        " atomic_radius":243.,
        "metalloid?":False,
        "electron_affinity":48.4,
        "pearson_electronegativity":233.6,
        "Z":19,
        "hardness":185.2,
}
    "He": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":0,
        "group":18,
        "actinide?":False,
        "nonmetal?":True,
        "period":1,
        "pauling_electronegativity":None,
        "nobleGas?":True,
        "abbreviation":"He",
        "ionization_energy":2372.3,
        " atomic_radius":31.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":1186.15,
        "Z":2,
        "hardness":1186.15,
}
    "Mg": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":2,
        "actinide?":False,
        "nonmetal?":False,
        "period":3,
        "pauling_electronegativity":1.31,
        "nobleGas?":False,
        "abbreviation":"Mg",
        "ionization_energy":737.7,
        " atomic_radius":145.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":368.85,
        "Z":12,
        "hardness":368.85,
}
    "Mo": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":6,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":2.16,
        "nobleGas?":False,
        "abbreviation":"Mo",
        "ionization_energy":684.3,
        " atomic_radius":190.,
        "metalloid?":False,
        "electron_affinity":71.9,
        "pearson_electronegativity":378.1,
        "Z":42,
        "hardness":306.2,
}
    "Mn": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":7,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.55,
        "nobleGas?":False,
        "abbreviation":"Mn",
        "ionization_energy":717.3,
        " atomic_radius":161.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":358.65,
        "Z":25,
        "hardness":358.65,
}
    "O": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":16,
        "actinide?":False,
        "nonmetal?":True,
        "period":2,
        "pauling_electronegativity":3.44,
        "nobleGas?":False,
        "abbreviation":"O",
        "ionization_energy":1313.9,
        " atomic_radius":48.,
        "metalloid?":False,
        "electron_affinity":141.,
        "pearson_electronegativity":727.5,
        "Z":8,
        "hardness":586.4,
}
    "S": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":16,
        "actinide?":False,
        "nonmetal?":True,
        "period":3,
        "pauling_electronegativity":2.58,
        "nobleGas?":False,
        "abbreviation":"S",
        "ionization_energy":999.6,
        " atomic_radius":88.,
        "metalloid?":False,
        "electron_affinity":2.e2,
        "pearson_electronegativity":6.e2,
        "Z":16,
        "hardness":4.e2,
}
    "W": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":6,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.36,
        "nobleGas?":False,
        "abbreviation":"W",
        "ionization_energy":770.,
        " atomic_radius":193.,
        "metalloid?":False,
        "electron_affinity":78.6,
        "pearson_electronegativity":424.,
        "Z":74,
        "hardness":346.,
}
    "Zn": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":12,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.65,
        "nobleGas?":False,
        "abbreviation":"Zn",
        "ionization_energy":906.4,
        " atomic_radius":142.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":453.2,
        "Z":30,
        "hardness":453.2,
}
    "Eu": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":None,
        "nobleGas?":False,
        "abbreviation":"Eu",
        "ionization_energy":547.1,
        " atomic_radius":231.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":299.,
        "Z":63,
        "hardness":249.,
}
    "Zr": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":4,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":1.33,
        "nobleGas?":False,
        "abbreviation":"Zr",
        "ionization_energy":640.1,
        " atomic_radius":206.,
        "metalloid?":False,
        "electron_affinity":41.1,
        "pearson_electronegativity":340.6,
        "Z":40,
        "hardness":299.5,
}
    "Er": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.24,
        "nobleGas?":False,
        "abbreviation":"Er",
        "ionization_energy":589.3,
        " atomic_radius":226.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":320.,
        "Z":68,
        "hardness":270.,
}
    "Ni": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":10,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.91,
        "nobleGas?":False,
        "abbreviation":"Ni",
        "ionization_energy":737.1,
        " atomic_radius":149.,
        "metalloid?":False,
        "electron_affinity":112.,
        "pearson_electronegativity":424.6,
        "Z":28,
        "hardness":312.6,
}
    "Na": {
        "lanthanide?":False,
        "alkali_metal?":True,
        "valence":1,
        "group":1,
        "actinide?":False,
        "nonmetal?":False,
        "period":3,
        "pauling_electronegativity":0.93,
        "nobleGas?":False,
        "abbreviation":"Na",
        "ionization_energy":495.8,
        " atomic_radius":190.,
        "metalloid?":False,
        "electron_affinity":52.8,
        "pearson_electronegativity":274.3,
        "Z":11,
        "hardness":221.5,
}
    "Nb": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":5,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":1.6,
        "nobleGas?":False,
        "abbreviation":"Nb",
        "ionization_energy":652.1,
        " atomic_radius":198.,
        "metalloid?":False,
        "electron_affinity":86.1,
        "pearson_electronegativity":369.1,
        "Z":41,
        "hardness":283.,
}
    "Nd": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.14,
        "nobleGas?":False,
        "abbreviation":"Nd",
        "ionization_energy":533.1,
        " atomic_radius":206.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":292.,
        "Z":60,
        "hardness":242.,
}
    "Ne": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":0,
        "group":18,
        "actinide?":False,
        "nonmetal?":True,
        "period":2,
        "pauling_electronegativity":None,
        "nobleGas?":True,
        "abbreviation":"Ne",
        "ionization_energy":2080.7,
        " atomic_radius":38.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":1040.35,
        "Z":10,
        "hardness":1040.35,
}
    "Np": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":None,
        "actinide?":True,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":1.36,
        "nobleGas?":False,
        "abbreviation":"Np",
        "ionization_energy":604.5,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":93,
        "hardness":None,
}
    "Fr": {
        "lanthanide?":False,
        "alkali_metal?":True,
        "valence":1,
        "group":1,
        "actinide?":False,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":0.7,
        "nobleGas?":False,
        "abbreviation":"Fr",
        "ionization_energy":380.,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":87,
        "hardness":None,
}
    "Fe": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":8,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.83,
        "nobleGas?":False,
        "abbreviation":"Fe",
        "ionization_energy":762.5,
        " atomic_radius":156.,
        "metalloid?":False,
        "electron_affinity":15.7,
        "pearson_electronegativity":389.1,
        "Z":26,
        "hardness":373.4,
}
    "B": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":13,
        "actinide?":False,
        "nonmetal?":False,
        "period":2,
        "pauling_electronegativity":2.04,
        "nobleGas?":False,
        "abbreviation":"B",
        "ionization_energy":800.6,
        " atomic_radius":87.,
        "metalloid?":True,
        "electron_affinity":26.7,
        "pearson_electronegativity":413.6,
        "Z":5,
        "hardness":387.,
}
    "F": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":1,
        "group":17,
        "actinide?":False,
        "nonmetal?":True,
        "period":2,
        "pauling_electronegativity":3.98,
        "nobleGas?":False,
        "abbreviation":"F",
        "ionization_energy":1681.,
        " atomic_radius":42.,
        "metalloid?":False,
        "electron_affinity":328.,
        "pearson_electronegativity":1005.,
        "Z":9,
        "hardness":677.,
}
    "Sr": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":2,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":0.95,
        "nobleGas?":False,
        "abbreviation":"Sr",
        "ionization_energy":549.5,
        " atomic_radius":219.,
        "metalloid?":False,
        "electron_affinity":5.03,
        "pearson_electronegativity":277.3,
        "Z":38,
        "hardness":272.2,
}
    "N": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":15,
        "actinide?":False,
        "nonmetal?":True,
        "period":2,
        "pauling_electronegativity":3.04,
        "nobleGas?":False,
        "abbreviation":"N",
        "ionization_energy":1402.3,
        " atomic_radius":56.,
        "metalloid?":False,
        "electron_affinity":7.,
        "pearson_electronegativity":705.,
        "Z":7,
        "hardness":698.,
}
    "Kr": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":18,
        "actinide?":False,
        "nonmetal?":True,
        "period":4,
        "pauling_electronegativity":3.,
        "nobleGas?":True,
        "abbreviation":"Kr",
        "ionization_energy":1350.8,
        " atomic_radius":88.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":675.4,
        "Z":36,
        "hardness":675.4,
}
    "Si": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":14,
        "actinide?":False,
        "nonmetal?":False,
        "period":3,
        "pauling_electronegativity":1.9,
        "nobleGas?":False,
        "abbreviation":"Si",
        "ionization_energy":786.5,
        " atomic_radius":111.,
        "metalloid?":True,
        "electron_affinity":133.6,
        "pearson_electronegativity":460.,
        "Z":14,
        "hardness":326.5,
}
    "Sn": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":14,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":1.96,
        "nobleGas?":False,
        "abbreviation":"Sn",
        "ionization_energy":708.6,
        " atomic_radius":145.,
        "metalloid?":False,
        "electron_affinity":107.3,
        "pearson_electronegativity":407.9,
        "Z":50,
        "hardness":300.6,
}
    "Sm": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.17,
        "nobleGas?":False,
        "abbreviation":"Sm",
        "ionization_energy":544.5,
        " atomic_radius":238.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":297.,
        "Z":62,
        "hardness":247.,
}
    "V": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":5,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.63,
        "nobleGas?":False,
        "abbreviation":"V",
        "ionization_energy":650.9,
        " atomic_radius":171.,
        "metalloid?":False,
        "electron_affinity":50.6,
        "pearson_electronegativity":350.7,
        "Z":23,
        "hardness":300.1,
}
    "Sc": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":3,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.36,
        "nobleGas?":False,
        "abbreviation":"Sc",
        "ionization_energy":633.1,
        " atomic_radius":184.,
        "metalloid?":False,
        "electron_affinity":18.1,
        "pearson_electronegativity":325.6,
        "Z":21,
        "hardness":307.5,
}
    "Sb": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":15,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":2.05,
        "nobleGas?":False,
        "abbreviation":"Sb",
        "ionization_energy":834.,
        " atomic_radius":133.,
        "metalloid?":True,
        "electron_affinity":103.2,
        "pearson_electronegativity":469.,
        "Z":51,
        "hardness":365.,
}
    "Se": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":16,
        "actinide?":False,
        "nonmetal?":True,
        "period":4,
        "pauling_electronegativity":2.55,
        "nobleGas?":False,
        "abbreviation":"Se",
        "ionization_energy":941.,
        " atomic_radius":103.,
        "metalloid?":False,
        "electron_affinity":195.,
        "pearson_electronegativity":568.,
        "Z":34,
        "hardness":373.,
}
    "Co": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":9,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.88,
        "nobleGas?":False,
        "abbreviation":"Co",
        "ionization_energy":760.4,
        " atomic_radius":152.,
        "metalloid?":False,
        "electron_affinity":63.7,
        "pearson_electronegativity":412.,
        "Z":27,
        "hardness":348.4,
}
    "Cl": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":17,
        "actinide?":False,
        "nonmetal?":True,
        "period":3,
        "pauling_electronegativity":3.16,
        "nobleGas?":False,
        "abbreviation":"Cl",
        "ionization_energy":1251.2,
        " atomic_radius":79.,
        "metalloid?":False,
        "electron_affinity":349.,
        "pearson_electronegativity":800.1,
        "Z":17,
        "hardness":451.1,
}
    "Ca": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":2,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.,
        "nobleGas?":False,
        "abbreviation":"Ca",
        "ionization_energy":589.8,
        " atomic_radius":194.,
        "metalloid?":False,
        "electron_affinity":2.37,
        "pearson_electronegativity":296.1,
        "Z":20,
        "hardness":293.7,
}
    "Ce": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":4,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.12,
        "nobleGas?":False,
        "abbreviation":"Ce",
        "ionization_energy":534.4,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":292.,
        "Z":58,
        "hardness":242.,
}
    "Xe": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":18,
        "actinide?":False,
        "nonmetal?":True,
        "period":5,
        "pauling_electronegativity":2.6,
        "nobleGas?":True,
        "abbreviation":"Xe",
        "ionization_energy":1170.4,
        " atomic_radius":108.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":585.2,
        "Z":54,
        "hardness":585.2,
}
    "Lu": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":3,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.27,
        "nobleGas?":False,
        "abbreviation":"Lu",
        "ionization_energy":523.5,
        " atomic_radius":217.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":287.,
        "Z":71,
        "hardness":237.,
}
    "Cs": {
        "lanthanide?":False,
        "alkali_metal?":True,
        "valence":1,
        "group":1,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":0.79,
        "nobleGas?":False,
        "abbreviation":"Cs",
        "ionization_energy":375.7,
        " atomic_radius":298.,
        "metalloid?":False,
        "electron_affinity":45.5,
        "pearson_electronegativity":210.6,
        "Z":55,
        "hardness":165.1,
}
    "Cr": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":6,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.66,
        "nobleGas?":False,
        "abbreviation":"Cr",
        "ionization_energy":652.9,
        " atomic_radius":166.,
        "metalloid?":False,
        "electron_affinity":64.3,
        "pearson_electronegativity":358.6,
        "Z":24,
        "hardness":294.3,
}
    "Cu": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":2,
        "group":11,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.9,
        "nobleGas?":False,
        "abbreviation":"Cu",
        "ionization_energy":745.5,
        " atomic_radius":145.,
        "metalloid?":False,
        "electron_affinity":118.4,
        "pearson_electronegativity":431.9,
        "Z":29,
        "hardness":313.5,
}
    "La": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.1,
        "nobleGas?":False,
        "abbreviation":"La",
        "ionization_energy":538.1,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":48.,
        "pearson_electronegativity":293.,
        "Z":57,
        "hardness":245.,
}
    "Li": {
        "lanthanide?":False,
        "alkali_metal?":True,
        "valence":1,
        "group":1,
        "actinide?":False,
        "nonmetal?":False,
        "period":2,
        "pauling_electronegativity":0.98,
        "nobleGas?":False,
        "abbreviation":"Li",
        "ionization_energy":520.2,
        " atomic_radius":167.,
        "metalloid?":False,
        "electron_affinity":59.6,
        "pearson_electronegativity":289.9,
        "Z":3,
        "hardness":230.3,
}
    "Tl": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":13,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.62,
        "nobleGas?":False,
        "abbreviation":"Tl",
        "ionization_energy":589.4,
        " atomic_radius":156.,
        "metalloid?":False,
        "electron_affinity":19.2,
        "pearson_electronegativity":304.3,
        "Z":81,
        "hardness":285.1,
}
    "Tm": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.25,
        "nobleGas?":False,
        "abbreviation":"Tm",
        "ionization_energy":596.7,
        " atomic_radius":222.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":323.,
        "Z":69,
        "hardness":273.,
}
    "Th": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":None,
        "actinide?":True,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":1.3,
        "nobleGas?":False,
        "abbreviation":"Th",
        "ionization_energy":587.,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":90,
        "hardness":None,
}
    "Ti": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":4,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":1.54,
        "nobleGas?":False,
        "abbreviation":"Ti",
        "ionization_energy":658.8,
        " atomic_radius":176.,
        "metalloid?":False,
        "electron_affinity":7.6,
        "pearson_electronegativity":333.2,
        "Z":22,
        "hardness":325.6,
}
    "Te": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":16,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":2.1,
        "nobleGas?":False,
        "abbreviation":"Te",
        "ionization_energy":869.3,
        " atomic_radius":123.,
        "metalloid?":True,
        "electron_affinity":190.2,
        "pearson_electronegativity":529.8,
        "Z":52,
        "hardness":339.6,
}
    "Tb": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":None,
        "nobleGas?":False,
        "abbreviation":"Tb",
        "ionization_energy":565.8,
        " atomic_radius":225.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":308.,
        "Z":65,
        "hardness":258.,
}
    "Tc": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":7,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":1.9,
        "nobleGas?":False,
        "abbreviation":"Tc",
        "ionization_energy":702.,
        " atomic_radius":183.,
        "metalloid?":False,
        "electron_affinity":53.,
        "pearson_electronegativity":378.,
        "Z":43,
        "hardness":324.,
}
    "Ta": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":5,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.5,
        "nobleGas?":False,
        "abbreviation":"Ta",
        "ionization_energy":761.,
        " atomic_radius":2.e2,
        "metalloid?":False,
        "electron_affinity":31.,
        "pearson_electronegativity":396.,
        "Z":73,
        "hardness":365.,
}
    "Yb": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":None,
        "nobleGas?":False,
        "abbreviation":"Yb",
        "ionization_energy":603.4,
        " atomic_radius":222.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":327.,
        "Z":70,
        "hardness":277.,
}
    "Dy": {
        "lanthanide?":True,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":1.22,
        "nobleGas?":False,
        "abbreviation":"Dy",
        "ionization_energy":573.,
        " atomic_radius":228.,
        "metalloid?":False,
        "electron_affinity":50.,
        "pearson_electronegativity":311.,
        "Z":66,
        "hardness":262.,
}
    "I": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":7,
        "group":17,
        "actinide?":False,
        "nonmetal?":True,
        "period":5,
        "pauling_electronegativity":2.66,
        "nobleGas?":False,
        "abbreviation":"I",
        "ionization_energy":1008.4,
        " atomic_radius":115.,
        "metalloid?":False,
        "electron_affinity":295.2,
        "pearson_electronegativity":651.8,
        "Z":53,
        "hardness":356.6,
}
    "U": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":None,
        "actinide?":True,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":1.38,
        "nobleGas?":False,
        "abbreviation":"U",
        "ionization_energy":597.6,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":92,
        "hardness":None,
}
    "Y": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":3,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":1.22,
        "nobleGas?":False,
        "abbreviation":"Y",
        "ionization_energy":6.e2,
        " atomic_radius":212.,
        "metalloid?":False,
        "electron_affinity":29.6,
        "pearson_electronegativity":3.1e2,
        "Z":39,
        "hardness":2.9e2,
}
    "Ac": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":None,
        "actinide?":True,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":1.1,
        "nobleGas?":False,
        "abbreviation":"Ac",
        "ionization_energy":499.,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":89,
        "hardness":None,
}
    "Ag": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":1,
        "group":11,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":1.93,
        "nobleGas?":False,
        "abbreviation":"Ag",
        "ionization_energy":731.,
        " atomic_radius":165.,
        "metalloid?":False,
        "electron_affinity":125.6,
        "pearson_electronegativity":428.3,
        "Z":47,
        "hardness":302.7,
}
    "Ir": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":6,
        "group":9,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.2,
        "nobleGas?":False,
        "abbreviation":"Ir",
        "ionization_energy":880.,
        " atomic_radius":180.,
        "metalloid?":False,
        "electron_affinity":151.,
        "pearson_electronegativity":516.,
        "Z":77,
        "hardness":365.,
}
    "Am": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":4,
        "group":None,
        "actinide?":True,
        "nonmetal?":False,
        "period":7,
        "pauling_electronegativity":1.3,
        "nobleGas?":False,
        "abbreviation":"Am",
        "ionization_energy":578.,
        " atomic_radius":None,
        "metalloid?":False,
        "electron_affinity":None,
        "pearson_electronegativity":None,
        "Z":95,
        "hardness":None,
}
    "Al": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":13,
        "actinide?":False,
        "nonmetal?":False,
        "period":3,
        "pauling_electronegativity":1.61,
        "nobleGas?":False,
        "abbreviation":"Al",
        "ionization_energy":577.5,
        " atomic_radius":118.,
        "metalloid?":False,
        "electron_affinity":42.5,
        "pearson_electronegativity":310.,
        "Z":13,
        "hardness":267.5,
}
    "As": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":15,
        "actinide?":False,
        "nonmetal?":False,
        "period":4,
        "pauling_electronegativity":2.18,
        "nobleGas?":False,
        "abbreviation":"As",
        "ionization_energy":947.,
        " atomic_radius":114.,
        "metalloid?":True,
        "electron_affinity":78.,
        "pearson_electronegativity":512.,
        "Z":33,
        "hardness":435.,
}
    "Ar": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":0,
        "group":18,
        "actinide?":False,
        "nonmetal?":True,
        "period":3,
        "pauling_electronegativity":None,
        "nobleGas?":True,
        "abbreviation":"Ar",
        "ionization_energy":1520.6,
        " atomic_radius":71.,
        "metalloid?":False,
        "electron_affinity":0.,
        "pearson_electronegativity":760.3,
        "Z":18,
        "hardness":760.3,
}
    "Au": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":5,
        "group":11,
        "actinide?":False,
        "nonmetal?":False,
        "period":6,
        "pauling_electronegativity":2.54,
        "nobleGas?":False,
        "abbreviation":"Au",
        "ionization_energy":890.1,
        " atomic_radius":174.,
        "metalloid?":False,
        "electron_affinity":222.8,
        "pearson_electronegativity":556.5,
        "Z":79,
        "hardness":333.6,
}
    "At": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":7,
        "group":17,
        "actinide?":False,
        "nonmetal?":True,
        "period":6,
        "pauling_electronegativity":2.2,
        "nobleGas?":False,
        "abbreviation":"At",
        "ionization_energy":920.,
        " atomic_radius":127.,
        "metalloid?":False,
        "electron_affinity":270.1,
        "pearson_electronegativity":595.,
        "Z":85,
        "hardness":325.,
}
    "In": {
        "lanthanide?":False,
        "alkali_metal?":False,
        "valence":3,
        "group":13,
        "actinide?":False,
        "nonmetal?":False,
        "period":5,
        "pauling_electronegativity":1.78,
        "nobleGas?":False,
        "abbreviation":"In",
        "ionization_energy":558.3,
        " atomic_radius":156.,
        "metalloid?":False,
        "electron_affinity":28.9,
        "pearson_electronegativity":293.6,
        "Z":49,
        "hardness":264.7,
}
}
